### ISSUE TITLE
About self-distillation training strategy

### ISSUE THREAD

**Issue by Vincent-luo** [Luodian/RelateAnything#14]
Thanks for your excellent work! And I have a question about the training strategy. In the [report](https://arxiv.org/abs/2302.02651) you mentioned, it uses self-distillation with soft labels. I wonder if you used this to train the RAM model and how much improvement will this technique bring?

**Comment by franciszzj** [comment]
Thank you for your interest in our project.
We did not use self-distillation with soft labels. We only used the labels annotated in the PSG dataset to train the Relate Anything model.
