### ISSUE TITLE
Is the demo on the HuggingFace website using CPU or GPU to inference?

### ISSUE THREAD

**Issue by xiaozhuka** [Luodian/RelateAnything#2]
Is the demo on the HuggingFace website using CPU or GPU to inference? 

Testing with sample data is a little too slow.
It took bout 500s to show the result.

What about the demo on Gradio, it's better. About 10s.

**Comment by Jingkang50** [comment]
Thank you for your interest in the project! Actually we don't have budget to get GPU support from huggingface so we can only use CPU there, but the gradio demo is built on our own server with GPU.
